# -*- coding: utf-8 -*-
"""Breast_cancer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1anoRYLcZDxbDBL-AJBn83SV2MoLtoVrf
"""

from sklearn.datasets import load_breast_cancer
data = load_breast_cancer()

import pandas as pd
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.cluster import KMeans
from sklearn.metrics import classification_report
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree

df = pd.DataFrame(data.data, columns = data.feature_names ).astype(float)

df.head()

len(df.columns)

df.columns

plt.figure(figsize = (25 , 12))
sns.heatmap(df.corr(), annot=True, fmt='.2f', cmap='RdGy')
plt.show()

scaler = StandardScaler()
scaled_values = scaler.fit_transform(df)

sse = []
k_values = range(1,11)

for k in k_values:
  kmeans = KMeans(n_clusters = k, n_init=10, random_state=42)
  kmeans.fit(scaled_values)
  sse.append(kmeans.inertia_)

labels = kmeans.labels_

plt.scatter(scaled_values[:, 0], scaled_values[:, 1], c=labels, cmap='viridis')
plt.xlabel('Feature 1')
plt.ylabel('Feature 2')
plt.title('K-means Clustering')
plt.show()

labels_df = pd.DataFrame(labels, columns = ['cluster label'])

df_labeled = pd.concat([df, labels_df], axis =1)

df_labeled.head()

X = df_labeled[df_labeled.columns[:-1]].values
Y = df_labeled[df_labeled.columns[-1]].values

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)

model = DecisionTreeClassifier()

model.fit(x_train, y_train)

y_pred = model.predict(x_test)

report =classification_report(y_test, y_pred)

print(report)

plt.figure(figsize = (25, 20))

class_names = [str(label) for label in np.unique(labels)]

tree.plot_tree(model, filled = True, rounded = True, class_names = class_names, feature_names = data.feature_names)

plt.show()

y_pred = np.array(y_pred)
y_test = np.array(y_test)

indices = np.arange(len(y_test))

plt.figure(figsize=(10, 5))
plt.plot(indices, y_test, color='blue', label='Actual')
plt.plot(indices, y_pred, color='red', label='Predicted')
plt.xlabel('Index')
plt.ylabel('Label')
plt.title('Actual vs Predicted Labels')
plt.legend()
plt.show()